version: "3"

services:
    hddmond:
        container_name: hddmond
        image: hddmond:latest
        ports: 
            - 8765:8765
            - 56567:56567
        restart: unless-stopped
        volumes: 
            - "./src/config:/etc/hddmon/config"
        privileged: true
    # hddmond-images:
    #     build: 
    #         context: .
    #         dockerfile: images-dockerfile 
    #     container_name: hddmond-images
    #     ports:
    #         - 84:80
    #     restart: unless-stopped
    #     volumes: 
    #         - "/etc/hddmon/images/:/www/"
    # hddmond-sshfs:
    #     build:
    #         context: .
    #         dockerfile: sshfs-dockerfile
    #     container_name: hddmon-imagesfs
    #     environment: 
    #         - PUID=1000
    #         - PGID=1000
    #         - PASSWORD_ACCESS=true
    #         - USER_PASSWORD=vel_images
    #         - USER_NAME=imuser
    #     ports:
    #         - "20201:2222"
    #     restart: unless-stopped
    #     volumes: 
    #         - "/etc/hddmon/images/:/images:ro"
    # hddmond-sftp:
    #     image: atmoz/sftp:alpine
    #     container_name: hddmond-upload
    #     ports:
    #         - "20202:22"
    #     restart: unless-stopped
    #     volumes:
    #         - "/etc/hddmon/images_new/:/home/images_new"
    #         - "/etc/hddmon/images/:/images:ro"
    #         - "/etc/hddmon/images_data/:/etc/sftp/:ro"
