version: "2"

services:
    hddmond:
        container_name: hddmond_old
        image: hddmond:latest
        environment:
            - "WEBSOCKET_PORT=8765"
            - "HDDMON_PORT=56567"
        ports: 
            - 8765:8765
            - 56567:56567
        # labels:
        #     caddy: "hddmon.${HOST_NAME}.${DOMAIN_NAME}:8765"
        #     caddy.reverse_proxy: "{{upstreams 8765}}"
        restart: unless-stopped
        command: "-v"
        volumes: 
            - "./src/config:/etc/hddmon/config"
        privileged: true
