version: "3"

services:
    hddmond:
        container_name: hddmond
        image: hddmond:latest
        ports: 
            - 8765:8765
            - 56567:56567
        restart: unless-stopped
        volumes: 
            - "./src/config:/etc/hddmon/config"
        privileged: true
